### PR TITLE
Bank api

### PR DESCRIPTION
**Pull request by jpcima**
It's another PR in a row after WOPN stuff
This supports bank API, to keep it marked as unstable for the time being.

It's for starting work on implementing the synthesizer's variant in OPN2

### CODE REVIEW

**Comment by Wohlstand** [comment]
Looks like some notes aren't correctly marked as blank...
Playing this 
[TRIP.MID.zip](https://github.com/Wohlstand/libOPNMIDI/files/2348324/TRIP.MID.zip)

Anyway, that is easy to fix:
```cpp
    // Old files are hadn't "blank" flag set, there are relying on kon/off zero equality
    if((ins.ms_sound_kon == 0) && (ins.ms_sound_koff == 0))
        ins.flags |= opnInstMeta::Flag_NoSound;
```

Or better... on WOPN library side when version is 2 or lower... As Version 3 will must have the flag be supported.

**Comment by Wohlstand** [comment]
Okay, I see what happens:
```
enum { Flag_Pseudo8op = 0x01, Flag_NoSound = 0x02 };
```
is not matching to:
```
typedef enum WOPN_InstrumentFlags
{
    /* Is a blank instrument entry */
    WOPN_Ins_IsBlank    = 0x01,

    /* Mask of the flags range */
    WOPN_Ins_ALL_MASK   = 0x01
} WOPN_InstrumentFlags;
```

**Comment by jpcima** [comment]
The pseudo-8op flag was existing!! oh damn
I remembered about meeting this already somewhere :grin:

**Comment by Wohlstand** [comment]
I kept this for future, but I wasn't implemented actual pseudo8op yet. But I thinking for this :smiley:

**Pull request merged**
